language: generic 

sudo: require

services:
  - docker

before_install:
  - docker build -t immanuelonum/docker-react -f Dockerfile.dev .

# script:
#   - docker run USERNAME/docker-react npm run test -- --coverage

script:
  - docker run -e CI=true immanuelonum/docker-react npm run test